Introduces Category entity
myfreecomm/myfinance-client-ruby pull request #19
Opened 2017-02-24 17:47 UTC by docStonehenge

WIP

2017-03-06 20:59 UTC, leandrost requested changes
Looks ok for me, but would be good take a look at these comments made by Hound.

2017-03-06 20:59 UTC, leandrost commented on lib/myfinance.rb
> +require 'myfinance/resources/category'
I agree with hound on this one

2017-03-06 20:59 UTC, leandrost commented on spec/lib/myfinance/client_spec.rb
> +  describe '#categories' do
+1

2017-03-06 20:59 UTC, leandrost commented on spec/lib/myfinance/entities/category_collection_spec.rb
> +require 'spec_helper'
+1 for double quotes

2017-03-06 20:59 UTC, leandrost commented on spec/lib/myfinance/client_spec.rb
> +    it 'instantiates a new Myfinance::Resources::Category' do
+1

2017-03-06 20:59 UTC, leandrost commented on spec/lib/myfinance/resources/category_spec.rb
> +        expect {
+1

2017-03-13 15:08 UTC, vagnerzampieri requested changes
Hound and conflicts.

2017-03-13 19:02 UTC, lmansur approved these changes

2017-03-13 20:12 UTC, merged

2017-03-13 21:04 UTC, rodrigotassinari commented
:shipit: released on [version 0.5.0](https://rubygems.org/gems/myfinance/versions/0.5.0)