Feature classification center classifications
myfreecomm/myfinance-client-ruby pull request #63
Opened 2018-09-03 17:59 UTC by vagnerzampieri

[ch15422](https://app.clubhouse.io/nexaas/story/15422/0-client-m%C3%BAltipla-classifica%C3%A7%C3%A3o-de-centro-de-custo-receita)

2018-09-03 18:48 UTC, lmansur commented on lib/myfinance/entities/credit_card.rb
> +      attribute :classification_center_classifications, Array[Hash]
`credit_card` does not have `classification_center_classifications`

2018-09-03 18:49 UTC, lmansur approved these changes

2018-09-04 14:20 UTC, leandrost requested changes

2018-09-04 14:20 UTC, leandrost commented on spec/lib/myfinance/entities/financial_transaction_spec.rb
> +                                          automatic_rule_related classification_center_id  classification_center_classifications
I agree with Hound on that

2018-09-04 16:39 UTC, dansdantas approved these changes

2018-09-05 17:36 UTC, leandrost approved these changes

2018-09-20 22:37 UTC, merged

2018-09-20 22:43 UTC, lmansur commented
:shipit: released on [version 1.8.0](https://rubygems.org/gems/myfinance/versions/1.8.0)